---
title: "Just to Avoid the Warning"
output: html_document
resource_files:
  - '.'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(reactable.static = TRUE)
```

```{css ref.label="styles", echo=FALSE}
```

```{r ref.label="font_styles", echo=FALSE}
```

```{r data, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(reactable)
library(htmltools)

# Load the data
data <- read_csv('~/Documents/repos/R/mexico_pop/datasets/1_Grupo_Quinq_00_RM.csv')

# Filter to only leave the desired state
bc <- data %>% 
  filter(CLAVE_ENT == 14,
         AÑO %in% c(1990, 2024)) %>% 
  select(-c(1:3),-5,-c(7:24)) %>% 
  group_by(NOM_MUN, AÑO) %>% 
  summarise(POB = sum(POB_TOTAL)) %>% 
  ungroup() %>% 
  pivot_wider(names_from = AÑO, values_from = POB, names_prefix = 'POB_') %>% 
  mutate(PCT_CHANGE = (POB_2024-POB_1990)/POB_1990)

columns <- c('Mun', 'Pop_1990', 'Pop_2024', 'Pct_Change')

colnames(bc) <- columns
```

```{r table, echo=FALSE}
tbl <- reactable(
  bc,
  pagination = TRUE,
  defaultSorted = 'Pct_Change',
  defaultColDef = colDef(headerClass = 'header', align = 'left'),
  columns = list(
    Mun = colDef(
      name = 'Municipality',
      format = colFormat(),
      width = 150
    ),
  Pop_1990 = colDef(
      name = '1990 Population',
      defaultSortOrder = 'desc',
      # Render the bar charts using a custom cell render function
      cell = function(value) {
        width <- paste0(value * 100 / max(bc$Pop_1990), '%')
        value <- format(value, big.mark = ',')
        value <- format(value, width = 9, justify = 'right')
        bar <- div(
          class = 'bar-chart',
          style = list(marginRight = '0.375rem'),
          div(class = 'bar', style = list(width = width, backgroundColor = '#3fc1c9'))
        )
        div(class = 'bar-cell', span(class = 'number', value), bar)
      }
    ),
  Pop_2024 = colDef(
      name = '2024 Population',
      defaultSortOrder = 'desc',
      cell = function(value) {
        width <- paste0(value * 100 / max(bc$Pop_2024), '%')
        value <- format(value, big.mark = ',')
        value <- format(value, width = 9, justify = 'right')
        bar <- div(
          class = 'bar-chart',
          style = list(marginRight = '0.375rem'),
          div(class = 'bar', style = list(width = width, backgroundColor = '#3fc1c9'))
        )
        div(class = 'bar-cell', span(class = 'number', value), bar)
      }
    ),
    Pct_Change = colDef(
      name = 'Percent Change 1990-2024',
      defaultSortOrder = 'desc',
      cell = function(value) {
        width <- paste0(round(value * 100 / max(bc$Pct_Change), 1), '%')
        value <- paste0(format(round(value * 100,1), nsmall = 1), '%')
        value <- format(value, width = 9, justify = 'right')
        bar <- div(
          class = 'bar-chart',
          style = list(marginRight = '0.375rem'),
          div(class = 'bar', style = list(width = width, backgroundColor = '#fc5185'))
        )
        div(class = 'bar-cell', span(class = 'number', value), bar)
      }
    ),
        html = TRUE
    ),
  compact = TRUE,
  class = "followers-tbl"
)

div(class = "twitter-followers",
  div(class = "followers-header",
    h2(class = "followers-title", "Changes in the Populations of Baja California's Municipalities, 1990-2024"),
    "Percent change in the population of Baja California's Municiplaities, 1990-2024"
  ),
  tbl
)
```

```{r font_styles, eval=FALSE, echo=FALSE}
htmltools::tags$link(href = ('https://fonts.googleapis.com/css2?family=Spline+Sans+Mono:ital,wght@0,300..700;1,300..700&family=Spline+Sans:wght@300..700&display=swap'), rel = 'stylesheet')
```

```{css styles, eval=FALSE, echo=FALSE}
.table-container {
  width: 80%;
  margin: 0 auto; /* Center the table horizontally */
}

.twitter-followers {
  margin: 0 auto;
  width: 800px;
  font-family: Spline Sans, "Helvetica Neue", Helvetica, Arial, sans-serif;
}

.followers-header {
  margin: 1.125rem 0;
  font-size: 1rem;
}

.followers-title {
  font-size: 1.25rem;
  font-weight: 600;
}

.followers-tbl {
  font-size: 0.875rem;
  line-height: 1.125rem;
}

.followers-tbl a {
  color: inherit;
  text-decoration: none;
}

.followers-tbl a:hover,
.followers-tbl a:focus {
  text-decoration: underline;
  text-decoration-thickness: max(1px, 0.0625rem);
}

.header {
  border-bottom: 2px solid #555;
  font-size: 0.8125rem;
  font-weight: 400;
  text-transform: uppercase;
}

.header:hover {
  background-color: #eee;
}

.bar-cell {
  display: flex;
  align-items: center;
}

.number {
  font-family: "Spline Sans Mono", Consolas, Monaco, monospace;
  font-size: 0.84375rem;
  white-space: pre;
}

.bar-chart {
  flex-grow: 1;
  margin-left: 0.375rem;
  height: 0.875rem;
}

.bar {
  height: 100%;
}
```